All the changes committed.
sushantyelpale/DALOptimizer pull request #2
Opened 2017-09-07 12:41 UTC by sushantyelpale

2017-09-07 13:35 UTC, kapilbhosale reviewed
@sushantyelpale Use OOPs properly.

2017-09-07 13:35 UTC, kapilbhosale commented on DALOptimizer/CSharpFile.cs
> +        public SyntaxTree SyntaxTree;
change it variable name must not be class name.

2017-09-07 13:35 UTC, kapilbhosale commented on DALOptimizer/CSharpFile.cs
> +        public SyntaxTree SyntaxTree;
http://www.oracle.com/technetwork/java/codeconventions-135099.html

2017-09-07 13:35 UTC, kapilbhosale commented on DALOptimizer/CSharpFile.cs
> +            this.SyntaxTree = p.Parse(this.OriginalText, fileName);
Method logic should not be constructor.

2017-09-07 13:35 UTC, kapilbhosale commented on DALOptimizer/CSharpProject.cs
> +		public CSharpProject(Solution solution, string title, string fileName)
Make Functions for the code, don't write it in a constructor.

2017-09-07 13:35 UTC, kapilbhosale commented on DALOptimizer/MatchExpr.cs
> +﻿using System;
Remove unused files.

2017-09-07 13:35 UTC, kapilbhosale commented on DALOptimizer/MatchInvocation.cs
> +            if (invocation.Parent.GetType().Name.ToString() == "TypeDeclaration")
Use string from constant variables.

2017-09-07 13:35 UTC, kapilbhosale commented on DALOptimizer/MatchInvocation.cs
> +            Match FillExpr = expr1.Match(invocation);
avoid using unused var

2017-09-07 13:35 UTC, kapilbhosale commented on DALOptimizer/MatchInvocation.cs
> +            Match logErr = expr2.Match(invocation);
Avoid extra match if true is found.

2017-09-07 13:35 UTC, kapilbhosale commented on DALOptimizer/Program.cs
> +        public static void Main(string[] args)
Avoid writing logic in main.

2017-09-07 13:35 UTC, kapilbhosale commented on DALOptimizer/Program.cs
> +                {
dont use parenthesis if not needed.

2017-09-07 13:35 UTC, kapilbhosale commented on DALOptimizer/Program.cs
> +                    if (invocation.GetType().Name == "CatchClause")
var nodeTypes = ["CatchClause", "FieldDeclaration"];
foreach (var nodeType in nodeTypes){
if (invocation.GetType().Name == nodeType)
 +                    {
 +                        Mr.MatchExprStmt(invocation, file, astResolver);
 +                        continue;
 +                    }
}

2017-09-07 13:35 UTC, kapilbhosale commented on DALOptimizer/Program.cs
> +                    if (file.IndexOfFieldDecl.Count == 0 && file.IndexOfPropDecl.Count == 0 &&
don't write very long expressions.

2017-09-07 13:35 UTC, kapilbhosale commented on DALOptimizer/Program.cs
> +                                    string varName = expr.GetText().Split("()".ToCharArray())[1];
add classes and separate methods.

2017-09-07 13:35 UTC, kapilbhosale commented on DALOptimizer/Program.cs
> +                            ICSharpCode.NRefactory.PatternMatching.Match FillExpr = expr2.Match(expr);
if (Pat.FillExpr().Match(expr).Success){
script.Remove(expr, true);
continue;
}

2017-09-07 13:35 UTC, kapilbhosale commented on DALOptimizer/Solution.cs
> +                        case "{2150E333-8FDC-42A3-9474-1A3956D46DE8}": // Solution Folder
use `2150E333-8FDC-42A3-9474-1A3956D46DE81` as constant.

2017-09-07 13:51 UTC, akshaymohite commented on DALOptimizer/DALOpt.csproj
> +﻿<?xml version="1.0" encoding="utf-8"?>
read about `gitignore`

2017-09-08 05:41 UTC, sushantyelpale commented on DALOptimizer/MatchExpr.cs
> +﻿using System;
Removed All unused Files

2017-09-08 05:42 UTC, sushantyelpale commented on DALOptimizer/MatchInvocation.cs
> +            Match FillExpr = expr1.Match(invocation);
removed all unused Variables

2017-09-08 05:42 UTC, sushantyelpale commented on DALOptimizer/Program.cs
> +        public static void Main(string[] args)
Removed all Logic from Main

2017-09-08 11:46 UTC, akshaymohite requested changes
@sushantyelpale suggested few changes. Please take care of them.

2017-09-08 11:46 UTC, akshaymohite commented on DALOptimizer/CSharpFile.cs
> +            this.Project = project;
can be renamed as `this.project`

2017-09-08 11:46 UTC, akshaymohite commented on DALOptimizer/CSharpFile.cs
> +            this.FileName = fileName;
can be renamed as `this.fileName`

2017-09-08 11:46 UTC, akshaymohite commented on DALOptimizer/CSharpFile.cs
> +            this.OriginalText = File.ReadAllText(fileName);
can be renamed as `originalText`

2017-09-08 11:46 UTC, akshaymohite commented on DALOptimizer/CSharpFile.cs
> +            this.UnresolvedTypeSystemForFile = this.syntaxTree.ToTypeSystem();
can be renamed as `unresolvedTypeSystemForFile`

2017-09-08 11:46 UTC, akshaymohite commented on DALOptimizer/CSharpProject.cs
> +		public ICompilation Compilation;
@sushantyelpale rename all variable names in camel case with first letter in lower case.

2017-09-08 11:46 UTC, akshaymohite commented on DALOptimizer/MatchInvocation.cs
> +            else if (Pat.ConvertToInt32().Match(invocation).Success) { file.IndexOfExprStmt.Add((ExpressionStatement)invocation); }
@sushantyelpale wouldn't using `switch` be a better choice here?

2017-09-08 11:46 UTC, akshaymohite commented on DALOptimizer/MatchExpr.cs
> +        private void GlobalFieldDeclaraton(DocumentScript script, CSharpFile file)
type near `Declaraton`, probably `Declaration`?

2017-09-08 11:46 UTC, akshaymohite commented on DALOptimizer/MatchInvocation.cs
> +                if (invocation.GetType().Name == METHODDECLARARION)
@sushantyelpale no need to calculate `invocation.GetType().Nam` for all the `if` condition checks.
Calculate it once and then use `switch` case to perform the necessary operation.

2017-09-08 11:46 UTC, akshaymohite commented on DALOptimizer/MatchInvocation.cs
> +            if (sqlCmdstmt1.Success)
@sushantyelpale rename `sqlCmdstmt1` to make it more meaningful. Variables should be named which we can pronounce.

2017-09-08 11:46 UTC, akshaymohite commented on DALOptimizer/MatchInvocation.cs
> +            Match sqlCmdstmt2 = Pat.sqlCmdstmt2().Match(invocation);
@sushantyelpale rename `sqlCmdstmt2` to make it more meaningful. Variables should be named which we can pronounce.

2017-09-08 11:46 UTC, akshaymohite commented on DALOptimizer/PrintFunction.cs
> +                  solution.AllFiles.Count(f => f.IndexOfFieldDecl.Count > 0));
@sushantyelpale `f.IndexOfFieldDecl.Count` is performed twice, try to perform it only once if it recalculates it every time we call it.

2017-09-08 11:46 UTC, akshaymohite commented on DALOptimizer/PrintFunction.cs
> +            Console.WriteLine("Found {0} places to refactor Variable Declaration in {1} files.",
@sushantyelpale try to see if all these `Console.WriteLine` could be done dynamically (probably calling in a loop)?

2017-09-08 11:46 UTC, akshaymohite commented on DALOptimizer/Program.cs
> +            OpenFileDialog opnfd = new OpenFileDialog();
@sushantyelpale rename `opnfd` to make it more meaningful.

2017-09-08 11:46 UTC, akshaymohite commented on DALOptimizer/Program.cs
> +            Console.Write("Apply refactorings? ");
@sushantyelpale probably we should suggest here as end user has to type "yes" or "y" to apply refctoring?

2017-09-08 11:46 UTC, akshaymohite commented on DALOptimizer/Solution.cs
> +            this.Directory = Path.GetDirectoryName(fileName);
`this.directory`

2017-09-08 11:46 UTC, akshaymohite commented on DALOptimizer/Solution.cs
> +                            case "{2150E333-8FDC-42A3-9474-1A3956D46DE8}": // Solution Folder
@sushantyelpale why are these hard codings?

2017-09-08 11:46 UTC, akshaymohite commented on DALOptimizer/Solution.cs
> +                            case "{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}": // C# project
@sushantyelpale why are these hard codings?

2017-09-08 11:46 UTC, akshaymohite commented on DALOptimizer/bin/Debug/DALOpt.exe.config
> +</configuration>
fix line endings in the editor.

2017-09-08 11:46 UTC, akshaymohite commented on DALOptimizer/MatchExpr.cs
> +                if (Pat.ConvertToInt32().Match(expr).Success) { script.Remove(expr, true); continue; }
The block `{ script.Remove(expr, true); continue; }` is same for all `if` conditions. Can be done in a single line.

2017-09-08 11:46 UTC, akshaymohite commented on DALOptimizer/MatchExpr.cs
> +                if (Pat.StoredProc().Match(expr).Success) { script.Remove(expr, true); continue; }
Let's say `Pat.FillExpr().Match(expr).Success` evaluates to `true` and `script.Remove(expr, true); continue;` is performed.

Then, do we need to perform all these other `if` conditions?

2017-09-08 11:46 UTC, akshaymohite commented on DALOptimizer/MatchExpr.cs
> +                        script.Replace(expr, getDtSet);
Saw similar code in `VarDeclarationStmt` method as well. Can we refactor to avoid duplication?

2017-10-27 20:25 UTC, merged